### ISSUE TITLE
发送带有空格的命令不执行

### ISSUE THREAD

**Issue by LittleTurtle2333** [ht0Ruial/Jiyu_udp_attack#1]
已测试"","""",''均不执行

**Comment by ht0Ruial** [comment]
因为-c参数是利用极域自身的命令执行功能，运行环境类似于cmd，你可以在cmd上尝试一下要执行的命令，看看能否在本机上执行？如果本机执行不了，那么利用-c参数执行命令大概也是一样执行不了的。

不过我期待你能描述得更加清楚一些，把整个要执行的命令一起发到这里，我帮你看看哪里出了问题。

**Comment by LittleTurtle2333** [comment]
例如
ping 127.0.0.1 -t
taskkill /F /IM chrome.exe
...
都无法执行。

**Comment by hibos9872** [comment]
期待-c 更详细使用命令，目前带空格和"" 是无法执行，不知道怎么写才能执行。

**Comment by LittleTurtle2333** [comment]
@ht0Ruial 最近有时间看看吗？
