### ISSUE TITLE
想请教下如何发现这个漏洞的

### ISSUE THREAD

**Issue by gtf35** [ht0Ruial/Jiyu_udp_attack#2]
很好奇如何发现的这个漏洞，能介绍下大体的经过吗？

**Comment by ht0Ruial** [comment]
emmm起初只是想脱离屏幕控制的，分析本地端口时发现是学生端是通过udp协议来接受屏幕数据的，那我们限制学生端传入的的udp数据包就能脱屏了；
后面从网上的搞到了极域的安装包，然后就搭建了测试环境，在看教师端的功能时有个命令执行的，就很好奇这个实现方式，wireshark抓包后分析了一下，数据包用的是udp协议发送的，然后把关键的数据提取出来，接着写好脚本后在物理机上对测试环境中的一台学生机进行攻击，然后发现学生机执行了该数据包里的命令，后续又重发了几遍都能成功执行。我们知道，udp协议是一种无状态的协议，教师端只管发不管谁来接受；学生端估计也是只管接也不管是谁发的；所以问题就出现了，我们可以伪造一个udp协议的数据包发给学生机，就可以实现发送消息、任意命令执行了。

**Comment by gtf35** [comment]
明白了，之前重来没想过这会是 udp 的，可能是来自小时候的恐惧，以为很厉害。

再次感谢分享👍
