### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by iamyx-33** [ht0Ruial/Jiyu_udp_attack#3]
[-] error 请使用 -h 以获取命令帮助
>>> Jiyu_udp_attack.py -e g
SyntaxError: invalid syntax
>>>

**Comment by ht0Ruial** [comment]
请确认一下python版本是否为py3，然后再确认有没有修改过代码，比如不小心按了个空格tab之类的操作

**Comment by ht0Ruial** [comment]
还有就是这个错误提示消息是我写的，“[-] error 请使用 -h 以获取命令帮助”，程序并没有出错，但是你输入的参数有误，所以提示你使用-h查看帮助；另外出现“SyntaxError: invalid syntax”这个异常的话你需要好好检查一下我上面说的，不然的话你也可以下载并使用打包好的可执行文件，这样无需检查语法问题。
