### ISSUE TITLE
我想把重放攻击的功能添加到JiYu Trainer里，需要您的同意，是否可行？

### ISSUE THREAD

**Issue by imengyu** [ht0Ruial/Jiyu_udp_attack#6]
我想把重放攻击的功能添加到[JiYu Trainer](https://github.com/imengyu/JiYuTrainer)里。

我想把您的攻击python代码改写成c语言的，并且加一个用户界面，嵌入到JiYu Trainer里，这部分工作由我完成，不需要您亲自写代码参与。因为攻击的原理是您发明提供的，所以我会在做好的程序内署上您的名字以及项目链接。
这需要您的同意，是否可行？

**Comment by sdsgccali** [comment]
🉑以。

**Comment by ht0Ruial** [comment]
可以。

**Comment by imengyu** [comment]
感谢大佬，程序功能添加进去并且完成了，并且署上了您的名字
